module.exports = [
  { code: "en", label: "English" },
  { code: "id", label: "Bahasa Indonesia" },
  { code: "bn", label: "বাংলা" },
  { code: "fr", label: "Français" },
  { code: "tr", label: "Türkçe" },
  { code: "es", label: "Español" },
  { code: "de", label: "Deutsch" },
  { code: "ms", label: "Bahasa Melayu" },
  { code: "ha", label: "Hausa" },
  { code: "sw", label: "Kiswahili" },
  { code: "so", label: "Soomaali" },
  { code: "sq", label: "Shqip" },
  { code: "bs", label: "Bosanski" },
  { code: "ru", label: "Русский" },
  { code: "pt", label: "Português" },
  { code: "nl", label: "Nederlands" },
  { code: "it", label: "Italiano" },
  { code: "hr", label: "Hrvatski" },
  { code: "mk", label: "Македонски" },
  { code: "ro", label: "Română" },
];
